version: '3.7'

services:
  db:
    # set db name
    container_name: "go-mysql-demo_db"
    # mac m1 need to do
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test_database"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "123456"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    # set suer name
    container_name: "go-mysql-demo-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default:
volumes:
  mysql_data: